version: '3'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip_all
    # mongo-client:
    #     image: mongo
    #     # command: mongo mongodb://mongodb:27017
    #     depends_on:
    #       - mongodb